# Generated by Django 5.2.4 on 2025-08-04 13:53

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_fullname', models.CharField(max_length=150, unique=True, verbose_name='Nome completo')),
                ('client_phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Telefone')),
                ('neighborhood', models.CharField(max_length=200, verbose_name='Bairro')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
